const express = require('express');
const router = express.Router();
const { register, login, getMe, refreshToken,logout } = require('../controllers/authController');
const authenticateToken = require('../middleware/authMiddleware');
router.post('/register', register);
router.post('/login', login);
router.get('/me', authenticateToken, getMe);
router.post('/refresh', refreshToken);
router.post('/logout',logout);
module.exports = router;